const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
const productRoutes = require("./routes/productRoutes")
const userRoutes = require("./routes/userRoutes")
const authRoutes = require("./routes/authRoutes")
const cookieParser = require("cookie-parser")
require("dotenv").config()
const app = express()

app.use(express.json())
app.use(cookieParser())
app.use(cors())
mongoose.set("strictQuery", "false")
mongoose.connect(process.env.MONGODB_URI)
    .then(() => {
        app.listen(process.env.PORT || 5000, () => console.log("Server and database connected"))
    })
    .catch((err) => {
        console.log(err)
        console.log("Server and database failed connected")
    })

app.use(productRoutes)
app.use(userRoutes)
app.use(authRoutes)